version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    image: ${IMAGE_NAME}
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "${PORT}:${PORT}"
    command: python ./src/manage.py runserver 0.0.0.0:8090
    depends_on:
      - db

volumes:
  data: